### ISSUE TITLE
Case clause error thrown in Socket.Web.recv when connection is closed

### ISSUE THREAD

**Issue by novaugust** [meh/elixir-socket#22]
The error:
```
{{case_clause,nil},[{'Elixir.Socket.Web',recv,1,[{file,"lib/socket/web.ex"},{line,665}]}
```

I've run into this in a few places where doing a recv on a closed socket returns an `{ :ok, nil }` that can't be matched against. What's the thought behind translating `{:error, :closed}` to {:ok, xx}`, rather than passing it up verbatim? Is this something easily patched by passing the `error, closed` up, or is the `{:ok, nil}` a special flag somewhere that needs an OK even when the socket's closed?

**Comment by skattyadz** [comment]
I also found this strange. In my own code I even found myself doing this:

```elixir
nil ->
  raise Socket.Error, reason: :closed
```
