### ISSUE TITLE
Web.ping isn't working

### ISSUE THREAD

**Issue by skattyadz** [meh/elixir-socket#25]
Before I tried for a PR I wanted to run this past you. Correct me if I'm wrong, I'm new to elixir

[Web.ping](https://github.com/meh/elixir-socket/blob/master/lib/socket/web.ex#L787) passes `{:ping, cookie}` to [Web.send](https://github.com/meh/elixir-socket/blob/master/lib/socket/web.ex#L735). send has a guard `when data?(opcode)` which stops it from matching this call.

I also noticed that the next guard is `and opcode != :close`, which as far as I can tell can't serve a use as `:close` doesn't pass `data?`

Thanks

**Comment by meh** [comment]
You're right, and I have no clue why I did it like that, it should just check for it to not be `:close` because it's handled by `close/{1,2,3}`.

**Comment by skattyadz** [comment]
Ok, I'll see what I can do
