### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by crertel** [meh/elixir-socket#28]
There aren't any docs up on hex for this--would you want a PR to add more docs?

**Comment by meh** [comment]
That would be lovely.

**Comment by CrowdHailer** [comment]
How is this coming along? Are there docs in the works? Would you like more help with docs?

**Comment by meh** [comment]
There are docs in the code right now, they should be complete from what I recall, you just have to build them yourself with exdoc.

**Comment by CrowdHailer** [comment]
ok. In that case might I suggest that the docs in the readme are expanded just with a line or two to say build with exdoc to get docs. Save other people having the same thought. 

That said i am quite new to elixir so maybe it is obvious already

**Comment by ziban** [comment]
It would be awesome if we can find more documentation in the README. It would save so much agony

**Comment by bjz** [comment]
Having docs on Hex would be super helpful!

**Comment by crertel** [comment]
Eeek. I forgot I even had a subscription to this. I'll see what I can do, may take a bit. Sorry folks! :(

**Comment by jeznet** [comment]
This issue can be closed now as it is possible to access [the socket documentation on hexdocs](https://hexdocs.pm/socket/) via its [hex page](https://hex.pm/packages/socket).
