### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jhicks-camgian** [meh/elixir-socket#50]
When a license projects a vulgarity and says DWTFYWT, the first thing I do is change the license to read "Do Whatever You Want To."  :)

More seriously, some of us working saps can actually get hit with sexual harassment suits over including profanity in assemblies of code..

**Comment by crertel** [comment]
In that case, link to the WTFPL [license](http://www.wtfpl.net/). If they're serious about firing you over code you aren't responsible for, is it really that great a place to work anyways?

**Comment by jhicks-camgian** [comment]
It's the way things are today and not really even much companies can do about it.   A lawsuit-seeking employee makes a whine about something stupid in the name of "sexual harassment" and even the best companies are forced to act by law.   Yep, it's nuts out there.

**Comment by meh** [comment]
It just means the license is working, if I were a company I'd fire the person filing the complaint, and if the company accepts the complaint I'd rather not make their life easier using my software.

But I do feel for you being in the crossfire.

**Comment by crertel** [comment]
Yeah, I do feel you pain. :(

**Comment by OvermindDL1** [comment]
Issue working in government as well, which I basically am.  MIT or Public Domain perhaps?
