### ISSUE TITLE
Question: Does Socket.Web.recv block until further data is available from the server?

### ISSUE THREAD

**Issue by sahrizvi** [meh/elixir-socket#62]
Please consider the following snippet, which is to poll a WebSocket server for data using a tail recursive loop:
```
def loop(socket, user_id) do
    case socket |> Socket.Web.recv! do
      {:text, data} ->      
         #received incoming data from server
      {:ping, _ } ->
        socket |> Socket.Web.send!({:pong, ""})
      _ -> 
        IO.puts("catch all")
    end
    loop(socket, user_id)
  end
```

This continues to print the "catch all" message even when the server is not really sending any messages. Doesn't the call `socket |> Socket.Web.recv!` block until data is available from the server?  I tried to answer this by going through the code, but I couldn't find anything conclusive.

**Comment by meh** [comment]
Try and inspect the value it's passing, it should be blocking.

**Comment by sahrizvi** [comment]
I inspected the value. I'm getting `{:close, :abnormal, nil} `which perhaps means that the WS server has closed the connection (the WS server actually does this by design in my case). 
I understand this behaviour now. Thank a lot @meh !
