### ISSUE TITLE
incorrect example

### ISSUE THREAD

**Issue by nhooyr** [meh/elixir-socket#78]
https://hexdocs.pm/socket/Socket.html#listen/1-example

```elixir
{ :ok, server } = Socket.listen "tcp://*:1337"
client = server.accept!(packet: :line)
client.send(client.recv)
client.close
```

Shouldn't those lines use the protocol? E.g. something like `Socket.Protocol.Stream.accept!(server, packet: :line)`?

**Comment by meh** [comment]
Yeah, the example comes from when `Record` still existed, I'll update it.
